### ISSUE TITLE
Wrong controller angle?

### ISSUE THREAD

**Issue by vicvr** [LibreVR/RoboRevive#5]
I'm using RoboRevive with the free RoboRecallModKit and the hands are pointing about 45° downwards compared to the Vive controllers.

Now, since this is a mod-kit, I've managed to half-ass fix it for some cases (empty hand, pistol, shotgun) by re-positioning the controller mesh, but I have no idea what I'm doing and I couldn't find where the mesh is parented to the controller position for a more generic fix (as it doesn't seem to be in the VR_Pawn). Any idea how to do this properly?

Examples of my poor hacks to make this a bit less crappy:
![bp_defaulthand](https://cloud.githubusercontent.com/assets/26304576/23756848/4abf3246-04e5-11e7-9bb6-ccbdbbc6a3a4.png)
![controllermesh](https://cloud.githubusercontent.com/assets/26304576/23756847/4a86f890-04e5-11e7-85a2-65d93a7f0401.png)

**Comment by Armada651** [comment]
I indeed want to correct the angles together with replacing all instances of Touch Controllers with Vive Controllers. But so far I haven't had time for it yet, so if you want to give it a shot feel free to submit a PR with your suggested changes.

**Comment by xnurt** [comment]
For now, you can play on revive and adjust controller angles easily with the menus in OpenVR Advanced Settings.

I'm using something like:
    "TouchPitch" : -24.0,
    "TouchRoll" : 0.0,
    "TouchYaw" : -0.5

I think I modified Z & X very slightly too.

I suggest turning on hybrid grips so you can hold a gun without holding down the side buttons.. then open the steam menu, and you can see the ghost of the gun and vive wand at the same time. Makes it pretty quick and easy to line things up.

**Comment by vicvr** [comment]
@Armada651 not sure how to do that, as I've modified game assets (e.g. \RoboRecallModKit\RoboRecall\Plugins\RoboRevivePistol\Content\Prototype\Game\Gun_Pistol.uasset) and I have no idea if they can be packaged inside a mod. Simply recreating the folder structure from the base game inside the mod folder didn't seem to do the trick. Again, I have no idea what I'm doing, first time touching UE4 :)

**Comment by xnurt** [comment]
You have to play it through steam, using Revive. And openVR. When you go to the steam menu, there's an advanced tab, then a revive tab in the advanced menu. It'll let you configure those settings for control angles & position (as well as the hybrid grip option, which I love using for this game).

**Comment by Armada651** [comment]
@xnurt I think he was referring to my comment, not yours.

**Comment by SeanPhaphui** [comment]
@xnurt Is there a way to use Revive with the Unreal Editor Version, or do we have to buy it on the Oculus Store?

**Comment by Armada651** [comment]
@SeanPhaphui The Editor version only has the first mission, if you want to play the full game you need to buy it from the Oculus Store.

**Comment by Armada651** [comment]
@vicvr I now got around to try and fix this problem and I too am running into problems overriding base game assests like `BP_DefaultHand`. I'll be looking into this further, if I can't override these assets I will patch the SteamVR plugin itself to offset the angles.

**Comment by Armada651** [comment]
Okay, I figured it out, you can only override `BP_DefaultHand` by creating a custom VR pawn. And according  to the forums:

> Pawn mods only take affect inside missions launched from the mod menu. When you're in the starting menus or hub, you won't see the affects take place.

Basically the same problem as those early teleportation mods.

**Comment by Armada651** [comment]
Good news, I was able to fix it by creating modded weapons for Revive. As long as Revive is an active mod this will work even outside of the mod menu as it does not touch the VR pawn.

Fixed in commit d7598efb53b48af163ed5943ba2b3e95ba07324c.

**Comment by duke4e** [comment]
After trying out the v1.0, I must say that this just doesnt feel right.

**Comment by Armada651** [comment]
@duke4e The controllers should now be aligned with the gun handle, trigger and barrel. But since everyone holds their controllers differently it's hard to find angles that are comfortable for everyone.

For example, some people prefer the gun be rotated slightly inwards because they don't hold the controller straight ahead. In a future version I'll probably make these angles customizable, for now though just make sure you are holding your controllers straight.

**Comment by duke4e** [comment]
@Armada651 Thanks for your reply and thanks giving hope for future updates.

I completely understand the idea behind the angles, and was looking forward to try it out until I actually tried it. From my personal observation, old angles were more in line with any native Vive shooter (Serious Sam, etc...). Even the laser pointers for menus seem counter inuitive as opposed to Steam VR pointers.

As you said, the best solution would be to make this customizable.

For now I'll stick with older version of RoboRevive, since it mostly works as I prefer (except not being able to access the menu).

Keep up with great work!
